name: easy_dropdown
description: A Flutter dropdown component that provides a simple and customizable way to handle item selection with separate selected and unselected lists.
version: 0.0.1
homepage: https://github.com/yourusername/easy_dropdown

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


